# Generated by Django 5.1.6 on 2025-04-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0004_alter_employers_email_alter_employers_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='username',
            field=models.CharField(default='-', max_length=100, verbose_name='Логин'),
        ),
    ]
