# Generated by Django 5.1.6 on 2025-04-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0005_employers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_shedules',
            name='is_weekend',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
    ]
