# Generated by Django 5.1.6 on 2025-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0006_current_shedules_is_weekend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20, verbose_name='Наименование месяца')),
                ('alternate_name', models.CharField(max_length=2, null=True, verbose_name='Сокращенное наименование месяца')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
    ]
