# Generated by Django 5.1.6 on 2025-05-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0008_genders_employers_gender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_code',
            field=models.CharField(default=None, max_length=20, verbose_name='Код должности'),
        ),
    ]
