# Generated by Django 5.1.6 on 2025-05-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0009_posts_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_shedules',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='future_shedules',
            name='task_id',
        ),
        migrations.CreateModel(
            name='Task_Distributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.tasks')),
            ],
            options={
                'verbose_name': 'Распределение задач',
                'verbose_name_plural': 'Распределения задач ',
            },
        ),
    ]
