# Generated by Django 5.1.6 on 2025-05-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0010_remove_current_shedules_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_task_distributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.current_shedules')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.tasks')),
            ],
            options={
                'verbose_name': 'Текущее распределение задач',
                'verbose_name_plural': 'Текущие распределения задач ',
            },
        ),
        migrations.CreateModel(
            name='Future_task_distributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.future_shedules')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.tasks')),
            ],
            options={
                'verbose_name': 'Будущее распределение задач',
                'verbose_name_plural': 'Будущие распределения задач ',
            },
        ),
        migrations.DeleteModel(
            name='Task_Distributions',
        ),
    ]
