# Generated by Django 5.1.6 on 2025-05-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0011_current_task_distributions_future_task_distributions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_shedules',
            name='is_weekend',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
    ]
