# Generated by Django 5.1.6 on 2025-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0013_alter_future_shedules_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='is_stop',
            field=models.BooleanField(default=False, verbose_name='Стоп пожелайки'),
        ),
        migrations.AlterField(
            model_name='future_shedules',
            name='comment',
            field=models.TextField(default='', max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
