# Generated by Django 5.1.6 on 2025-05-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0014_divisions_is_stop_alter_future_shedules_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование изображения')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='employers',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.photos'),
        ),
    ]
