# Generated by Django 5.1.6 on 2025-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0016_alter_photos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
