# Generated by Django 5.1.6 on 2025-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0018_alter_employers_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='email',
        ),
        migrations.AddField(
            model_name='employers',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Phone'),
        ),
    ]
