# Generated by Django 5.1.6 on 2025-05-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0019_remove_employers_email_employers_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future_task_distributions',
            name='shedule_id',
        ),
        migrations.RemoveField(
            model_name='future_task_distributions',
            name='task_id',
        ),
        migrations.CreateModel(
            name='Current_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default='', max_length=255, null=True, verbose_name='Задача')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.current_shedules')),
            ],
            options={
                'verbose_name': 'Текущее распределение задач',
                'verbose_name_plural': 'Текущие распределения задач ',
            },
        ),
        migrations.CreateModel(
            name='Future_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default='', max_length=255, null=True, verbose_name='Задача')),
                ('shedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.future_shedules')),
            ],
            options={
                'verbose_name': 'Будущее распределение задач',
                'verbose_name_plural': 'Будущие распределения задач ',
            },
        ),
        migrations.DeleteModel(
            name='Current_task_distributions',
        ),
        migrations.DeleteModel(
            name='Future_task_distributions',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
