# Generated by Django 5.1.6 on 2025-12-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0020_remove_future_task_distributions_shedule_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_tasks',
            options={'verbose_name': 'Текущая задача', 'verbose_name_plural': 'Текущие задачи'},
        ),
        migrations.AlterModelOptions(
            name='future_tasks',
            options={'verbose_name': 'Будущая задача', 'verbose_name_plural': 'Будущие задачи'},
        ),
        migrations.CreateModel(
            name='Future_shedules_New_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_work', models.TimeField(verbose_name='Время начала смены')),
                ('end_work', models.TimeField(verbose_name='Время окончания смены')),
                ('comment', models.TextField(default='', max_length=255, null=True, verbose_name='Комментарий')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Выходной')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
                ('week_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.week_days')),
            ],
            options={
                'verbose_name': 'Будущее расписание Новый год',
                'verbose_name_plural': 'Будущие расписания Новый год',
            },
        ),
    ]
