# Generated by Django 5.1.6 on 2025-12-17 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0021_alter_current_tasks_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.TextField(default='', max_length=255, null=True, verbose_name='Пожелание')),
                ('employer_to', models.TextField(default='', max_length=255, null=True, verbose_name='Получатель')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
            ],
            options={
                'verbose_name': 'Пожелание',
                'verbose_name_plural': 'Пожелания',
            },
        ),
    ]
