# Generated by Django 5.1.6 on 2025-04-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100, verbose_name='Наименование подразделения')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('start_work', models.TimeField(verbose_name='Время начала работы')),
                ('end_work', models.TimeField(verbose_name='Время конца работы')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50, verbose_name='Наименование должности')),
            ],
        ),
        migrations.CreateModel(
            name='Week_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20, verbose_name='Наименование дня недели')),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(default='-', max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.divisions')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Наименование задачи')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
            ],
        ),
        migrations.CreateModel(
            name='Current_shedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_work', models.TimeField(verbose_name='Время начала смены')),
                ('end_work', models.TimeField(verbose_name='Время окончания смены')),
                ('comment', models.TextField(max_length=255, verbose_name='Комментарий')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.tasks')),
                ('week_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.week_days')),
            ],
        ),
    ]
