# Generated by Django 5.1.6 on 2025-04-15 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_shedules',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='employer_id',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.TextField(max_length=255, verbose_name='Наименование задачи'),
        ),
        migrations.CreateModel(
            name='Future_shedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_work', models.TimeField(verbose_name='Время начала смены')),
                ('end_work', models.TimeField(verbose_name='Время окончания смены')),
                ('comment', models.TextField(max_length=255, verbose_name='Комментарий')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.employers')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.tasks')),
                ('week_day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aup.week_days')),
            ],
        ),
    ]
