# Generated by Django 5.1.6 on 2025-04-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0002_remove_current_shedules_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_shedules',
            options={'verbose_name': 'Текущее расписание', 'verbose_name_plural': 'Текущие расписания'},
        ),
        migrations.AlterModelOptions(
            name='divisions',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='employers',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='future_shedules',
            options={'verbose_name': 'Будущее расписание', 'verbose_name_plural': 'Будущие расписания'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='week_days',
            options={'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AddField(
            model_name='week_days',
            name='alternate_name',
            field=models.CharField(max_length=2, null=True, verbose_name='Сокращенное наименование дня недели'),
        ),
    ]
