# Generated by Django 5.1.6 on 2025-04-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0003_alter_current_shedules_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='photo',
            field=models.CharField(max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
