# Generated by Django 5.1.6 on 2025-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0012_future_shedules_is_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_shedules',
            name='comment',
            field=models.TextField(default=' ', max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
