# Generated by Django 5.1.6 on 2025-05-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0015_photos_alter_employers_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
