# Generated by Django 5.1.6 on 2025-05-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0017_alter_employers_photo_delete_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
