# Generated by Django 5.1.6 on 2025-12-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0022_wishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='employer_to',
            field=models.TextField(default='-', max_length=255, verbose_name='Получатель'),
        ),
    ]
