# Generated by Django 5.1.6 on 2025-12-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0023_alter_wishes_employer_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='wishes',
            name='employer_from',
            field=models.TextField(default='-', max_length=255, verbose_name='Отправитель'),
        ),
    ]
