# Generated by Django 5.1.6 on 2025-12-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0024_remove_wishes_employer_id_wishes_employer_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='employer_from',
            field=models.TextField(default='', max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='employer_to',
            field=models.TextField(default='', max_length=255, verbose_name='Получатель'),
        ),
    ]
