# Generated by Django 5.1.6 on 2026-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aup', '0025_alter_wishes_employer_from_alter_wishes_employer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='birthday',
            field=models.DateField(default='2000-01-01', verbose_name='Дата рождения'),
        ),
    ]
